#!/usr/bin/env node
import { fileURLToPath } from 'url'
import { dirname, resolve } from 'path'
import { execSync } from 'child_process'

const __dirname = dirname(fileURLToPath(import.meta.url))
const commitMsg = process.argv[2]

try {
  execSync(`npx --no -- commitlint --edit ${commitMsg}`, { stdio: 'inherit' })
} catch (error) {
  process.exit(1)
} 